# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.7
  - 1.0
  - 1.1
  - nightly
matrix:
    allow_failures:
        - julia: nightly
        - julia: 0.7
notifications:
    email: false
after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("Stochatto")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia -e 'using Pkg; cd(Pkg.dir("Stochatto")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
